### ISSUE TITLE
Bad Request: too many requests

### ISSUE THREAD

**Issue by whowantblood** [reks-scripts/gw2ap#21]
Error Pop's up everytime i try to process my achievments (Sadface)

**Comment by lowtekn7** [comment]
@whowantblood Not sure what your comfort level is, but you can clone the project to your local machine and run it from there. The readme walks you through how to do it, but it assumes a certain level of competence.

**Comment by magnapeccatrix** [comment]
as of today, this is still a problem.

**Comment by reks-scripts** [comment]
I'll try to fix this, but for now, if you keep trying, it seems to start working within a couple of minutes.

**Comment by magnapeccatrix** [comment]
I think you received my message on reddit, thank you for taking a look!

**Comment by reks-scripts** [comment]
I'm going to close this because I'm pretty sure it's fixed now.  But please let me know if you see it happening again.  Thanks!
